config/routes.rb
Cuemaker::Application.routes.draw do
  resources :cues

  root to: "cues#index"
end

app/models/cue.rb
class Cue < ActiveRecord::Base
  attr_accessible :body
end

app/models/cue_pdf.rb
class CuePdf < Prawn::Document
  def initialize(cue)
    super(page_size: [220,140], :margin => [8,8,8,8], font: "Helvetica")
    @cue = cue
    body
  end
  
  def body
    @cue.body.split(/\n/).each do |cue|
      group do
        text cue, size: 8
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cues_controller.rb
class CuesController < ApplicationController
  # GET /cues
  # GET /cues.json
  def index
    @cues = Cue.all
    @cue = Cue.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cues }
    end
  end

  # GET /cues/1
  # GET /cues/1.json
  def show
    @cue = Cue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cue }
      format.pdf do
      pdf = CuePdf.new(@cue)
      send_data pdf.render, filename: "cuecard",
                            type: "application/pdf",
                            disposition: "inline"
    end
    end
  end

  # GET /cues/new
  # GET /cues/new.json
  def new
    @cue = Cue.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cue }
    end
  end

  # GET /cues/1/edit
  def edit
    @cue = Cue.find(params[:id])
  end

  # POST /cues
  # POST /cues.json
  def create
    @cue = Cue.new(params[:cue])

    respond_to do |format|
      if @cue.save
        format.html { redirect_to @cue, notice: 'Cue was successfully created.' }
        format.json { render json: @cue, status: :created, location: @cue }
      else
        format.html { render action: "new" }
        format.json { render json: @cue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cues/1
  # PUT /cues/1.json
  def update
    @cue = Cue.find(params[:id])

    respond_to do |format|
      if @cue.update_attributes(params[:cue])
        format.html { redirect_to @cue, notice: 'Cue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cues/1
  # DELETE /cues/1.json
  def destroy
    @cue = Cue.find(params[:id])
    @cue.destroy

    respond_to do |format|
      format.html { redirect_to cues_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cues_helper.rb
module CuesHelper
end

app/views/cues/_form.html.erb
<%= form_for(@cue) do |f| %>
  <% if @cue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cue.errors.count, "error") %> prohibited this cue from being saved:</h2>

      <ul>
      <% @cue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
      <%= f.text_area :body, placeholder: "Cue Card Content Here", rows:2, id:"expand" %>  
      <center>
      <%= f.submit "Create Your Cue Card Now!", class: "button success"%>  
      </center>
<% end %>

app/views/cues/edit.html.erb
<h1>Editing cue</h1>

<%= render 'form' %>

<%= link_to 'Show', @cue %> |
<%= link_to 'Back', cues_path %>

app/views/cues/index.html.erb
<div class="row">
<div class="nine mobile-four columns centered">
<h1 id="heading">CueMaker</h1>
<p class="subheader">Don't want to waste time making cuecards for your PW? You're at the right place (:</p>

<%= render 'form' %>

<dl class="tabs">
  <dd class="active"><a href="#how">How To Use</a></dd>
  <dd><a href="#about">About</a></dd>
</dl>
<ul class="tabs-content">
  <li class="active" id="howTab">
    <h6>What?</h6>
    <p>This app was created for the creation of printable, ready-made cue cards from plain text.</p>
    <h6>Requirements</h6>
    <ol>
      <li>Slides must be split by paragraphing.</li>
      <li>Note: Slides that can fit together on one piece of cue card will automatically by fitted together</li>
    </ol>
  </li>
  <li id="aboutTab">
    Name: Jethro Kuan <br>
    <p>Email: <%=link_to "jethrokuan95@gmail.com", "mailto:jethrokuan95@gmail.com"%></p>
    
    <p>Site code is freely available <%=link_to "here","https://github.com/jethrokuan/cuemaker"%></p>
    <p>My Website: <%=link_to "jethrokuan.1.ai", "http://jethrokuan.1.ai"%></p>
    Other Projects: <br>
    <ul>
      <li><%=link_to "Openlectures", "http://olweb.herokuapp.com"%></li>
      <li><%=link_to "Newsdaily", "http://newsdaily.herokuapp.com"%></li>
    </ul>
  </li>
</ul>
<hr>
<div class="row">
  <div class="six columns">
    &copy Jethro Kuan 2012
  </div>
  <div class="six columns">
    <div class="fb-like" data-href="http://cuemaker.herokuapp.com/" data-send="false" data-width="450" data-show-faces="true" data-font="arial"></div>    
  </div>
</div>
</div>
</div>
  
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=510921032252599";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));

$(document).ready(function() {
  $('#expand')
    .focus(function(){ this.rows=12 })
});
</script>

app/views/cues/new.html.erb
<h1>New cue</h1>

<%= render 'form' %>

<%= link_to 'Back', cues_path %>

app/views/cues/show.html.erb
<div class="row">
  <div class="nine mobile-four columns centered">
  <center>
    <h1 id="heading">Congratulations!</h1>
    <p class="subheading">Your cue card is ready!</p>
    <h5>Pasted Text</h5>
    <div id="pasted">
      <%=@cue.body%>
    </div>
    <p>Get it <%=link_to "here", cue_path(@cue, format: "pdf")%>!</p>
    </center>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	
	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
	
	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	
	<title><%= content_for?(:title) ? yield(:title) : "CueMaker" %></title>
  
	<!-- Included CSS Files -->
	<%= stylesheet_link_tag    "application" %>
	<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
	<!-- Included JS Files  -->
	<%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>